export const SET_LOADING = 'SET_LOADING';
export const SET_SIGNUP_SUCCESS = 'SET_SIGNUP_SUCCESS';
export const SET_SIGNUP_ERRORS = 'SET_SIGNUP_ERRORS';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERRORS = 'SET_LOGIN_ERRORS';
export const SET_LOGOUT_ERRORS = 'SET_LOGOUT_ERRORS';
export const SET_LOGOUT_SUCCESS = 'SET_LOGIN_SUCCESS';

